# Generated by Django 5.0.1 on 2024-01-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='modules',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='container',
            name='restart',
            field=models.BooleanField(default=False),
        ),
    ]
