# Generated by Django 5.0.1 on 2024-02-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_control', '0002_container_modules_container_restart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='modules',
        ),
        migrations.AddField(
            model_name='container',
            name='modules',
            field=models.ManyToManyField(blank=True, to='container_control.moduleslist'),
        ),
    ]
